### ISSUE TITLE
rider use bug

### ISSUE THREAD

**Issue by yuweni99** [magidc/ideavim-anyobject#5]
Hello, I encountered an issue in Reder's latest version 2025.3.0.1 where the "a" text variable cannot be used, such as using dia, daa, etc. Method parameters cannot be deleted, while other text variables can be used normally

**Comment by magidc** [comment]
Hi, thanks for feedback.
Other user has reported problems with Rider compatibility. It is a platform where the plugin was not fully tested.
I have released a beta version of the plugin. You can install it manually from Github [releases](https://github.com/magidc/ideavim-anyobject/releases/tag/2.0.5-beta).
I have fixed C# compatibility, it should now detect arguments/parameters, loops, conditionals. etc. I would appreciate if you test it for a few days and report feedback before I send a final version to marketplace.

**Comment by yuweni99** [comment]
Hello, there is still a problem deleting function parameters, such as "IdleAction. Add (DocumentManager. Init);". I tried to delete DocumentManager. Init using daa, but it doesn't work. There is no problem deleting it with regular function calls

**Comment by magidc** [comment]
Thx, I will take a look to the issue!

**Comment by magidc** [comment]
I have released a [beta version of the plugin](https://github.com/magidc/ideavim-anyobject/releases/tag/2.0.6-beta) that you can install manually, see [this](https://github.com/magidc/ideavim-anyobject#manual-installation).

It would be great if you install it and test it for a few days and providing me with feedback before the new version is sent to the Jetbrains marketplace

**Comment by yuweni99** [comment]
Thank you very much. After testing, it was found that the previous issue has been resolved

**Comment by magidc** [comment]
Great! Thank you very much for helping me to improve the plugin.
 If you don't mind, I would a appreciate a review on plugins [home page ](https://plugins.jetbrains.com/plugin/28333-vim-anyobject/edit/reviews) (unless you already did it, and a star on this Github repo.
